PORT = 8_080
STATIC = "static"
ASSETS = "static/assets"
UPLOAD = "static/uploads"
SECRET_KEY = "92086f0f1e255c334447d8e1760ef0a2f0afce5c377df2d7651f9520f3dcd1e7" #openssl rand -hex 32
ALGORITHM = "HS256"
LANG = "en"
FALLBACK_LANG = "en"
ACCESS_TOKEN_EXPIRE_MINUTES = 11_520
SQLITE_CACHE_SIZE = -2_097_152
SQLITE_BUSY_TIMEOUT = 60_000
DB_LOG = false
DO_NOT_VERIFY_AUTH_TOKEN = [ "login/login", "login/index" ]
CORE_TABLES = [
    "lang",
    "role",
    "user",
    "user_role",
    "app",
    "menu",
    "table",
    "menu_table",
    "role_app",
    "role_app_menu",
    "role_app_menu_table",
    "user_log",
    "custom_table",
    "custom_form",
    "column_level_access",
    "row_level_access",
    "translate_table",
    "translate_table_field"
]
ALLOW_CLI_RUN_QUERIES = false

[DATABASE]
drivername = "sqlite"
database = "ADMIN_DB"

[DATABASE-pg]
drivername = "postgresql + psycopg2"
hostname = "127.0.0.1"
port = 3_606
username = "root"
password = 1_234
database = "ADMIN_DB"

[REQUEST_LOG]
ACTIONS_TO_IGNORE = [
    "chk_token",
    "chk_session",
    "chkToken",
    "chkSession",
    "read",
    "r",
    "extrat__"
]
DO_NOT_STORE_DATA = true
SKIP_SPECIFIC_FIELDS-- = [ "req_data", "res_data", "new_data" ]

[BROADCAST_CHANGES]
ACTIONS = [ "create_update", "create", "update", "delete", "c", "u", "d" ]
